# Generated by Django 3.2.2 on 2021-05-08 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=75)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('mobno', models.IntegerField(blank=True, null=True)),
                ('instaid', models.CharField(max_length=75)),
                ('one', models.CharField(max_length=100)),
                ('two', models.CharField(max_length=100)),
                ('three', models.CharField(max_length=100)),
                ('four', models.CharField(max_length=100)),
                ('five', models.CharField(max_length=100)),
            ],
        ),
    ]
